# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveSmallIntegerField()),
                ('cores', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveSmallIntegerField()),
                ('free', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compType', models.PositiveSmallIntegerField(choices=[(1, 'Desktop'), (2, 'Laptop'), (3, 'Server')], default=1)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('compModel', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.CPU')),
                ('gpus', models.ManyToManyField(to='data.GPU')),
                ('hdds', models.ManyToManyField(to='data.HDD')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mac', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('sticks', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='network',
            field=models.ManyToManyField(to='data.Network'),
        ),
        migrations.AddField(
            model_name='machine',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.RAM'),
        ),
        migrations.AddField(
            model_name='machine',
            name='roles',
            field=models.ManyToManyField(to='data.Role'),
        ),
    ]
