# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cloudID',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='free',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='compModel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.CPU'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='gpus',
            field=models.ManyToManyField(blank=True, null=True, to='data.GPU'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hdds',
            field=models.ManyToManyField(blank=True, null=True, to='data.HDD'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='os',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.RAM'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='data.Role'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ram',
            name='sticks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
