# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20161014_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='cloudID',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='gpus',
            field=models.ManyToManyField(blank=True, to='data.GPU'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hdds',
            field=models.ManyToManyField(blank=True, to='data.HDD'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='roles',
            field=models.ManyToManyField(blank=True, to='data.Role'),
        ),
        migrations.AlterField(
            model_name='network',
            name='mac',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
